apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attt
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - api-hpa.yaml
  - worker-deployment.yaml
  - beat-deployment.yaml
  - ingress.yaml
